const KEY="rs-v3-stops",ORDER="rs-v3-order",ACTIVE="rs-v3-active";
let stops=JSON.parse(localStorage.getItem(KEY)||"[]"), orderIds=JSON.parse(localStorage.getItem(ORDER)||"[]"), active=localStorage.getItem(ACTIVE)==="1", filter="";
const meta={completed:["Concluído","#16a34a","green"],returnLater:["Retornar","#2563eb","blue"],pending:["Pendente","#f59e0b","orange"],notHome:["Não estava em casa","#dc2626","red"]};
const map=L.map("map").setView([-23.5505,-46.6333],13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map);
let routeLayer=null,userMarker=null;
const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const save=()=>localStorage.setItem(KEY,JSON.stringify(stops));
const remaining=()=>stops.filter(s=>s.status!=="completed");
function counts(){total.textContent=stops.length;done.textContent=stops.filter(s=>s.status==="completed").length;pending.textContent=stops.filter(s=>s.status==="pending").length;returns.textContent=stops.filter(s=>s.status==="returnLater").length}
function orderedRemaining(){const mapId=new Map(stops.map(s=>[s.id,s]));return orderIds.map(id=>mapId.get(id)).filter(Boolean).filter(s=>s.status!=="completed").concat(remaining().filter(s=>!orderIds.includes(s.id)))}
function render(){
 counts();routeState.textContent=active?"Rota em andamento":"Rota parada";routeHint.textContent=active?"Você pode adicionar uma parada e recalcular só o que falta.":"Adicione paradas e otimize.";document.querySelector(".live-dot").classList.toggle("on",active);
 const list=document.querySelector("#stopList");list.innerHTML="";
 let arr=filter?stops.filter(s=>s.status===filter):orderedRemaining();
 arr.forEach((s,i)=>{let [label,_,cl]=meta[s.status],el=document.createElement("button");el.className="stop";el.innerHTML=`<span class="num">${i+1}</span><span class="main"><span class="name">${esc(s.name||"Parada")}</span><br><span class="addr">${esc(s.address)}</span>${s.note?`<br><span class="addr">📝 ${esc(s.note)}</span>`:""}</span><span class="tag ${cl}">${label}</span>`;el.onclick=()=>openStop(s.id);list.appendChild(el)});
 showNext();map.eachLayer(l=>{if(l instanceof L.CircleMarker)map.removeLayer(l)});stops.forEach(s=>L.circleMarker([s.lat,s.lon],{radius:9,fillColor:meta[s.status][1],color:"#fff",weight:3,fillOpacity:1}).addTo(map).on("click",()=>openStop(s.id)));
}
function showNext(){const n=orderedRemaining()[0],box=document.querySelector("#nextCard");if(!active||!n){box.classList.add("hidden");return}box.classList.remove("hidden");box.innerHTML=`<div class="eyebrow">Próxima parada</div><div class="title">${esc(n.name||"Parada")}</div><div class="addr">${esc(n.address)}</div><div class="next-actions"><button class="go" onclick="navigateTo('${n.id}')">🧭 Navegar</button><button class="done" onclick="quickComplete('${n.id}')">✓ Concluído</button></div>`}
function closeModal(){modal.classList.add("hidden")}close.onclick=closeModal;
function openStop(id){let s=stops.find(x=>x.id===id);if(!s)return;selected=id;modalBody.innerHTML=`<h2>${esc(s.name||"Parada")}</h2><p style="color:var(--muted)">${esc(s.address)}</p><div class="field"><label>Observação</label><textarea id="note" rows="2">${esc(s.note)}</textarea></div><button id="saveNote" class="secondary full">Salvar observação</button><hr><p><b>Status</b></p><button class="status-btn green" data-st="completed">✓ Concluído</button><button class="status-btn blue" data-st="returnLater">↩ Retornar</button><button class="status-btn orange" data-st="pending">◷ Pendente</button><button class="status-btn red" data-st="notHome">⌂ Não estava em casa</button>`;modal.classList.remove("hidden");saveNote.onclick=()=>{s.note=note.value;save();closeModal();render()};document.querySelectorAll("[data-st]").forEach(b=>b.onclick=()=>{s.status=b.dataset.st;save();closeModal();render()})}
function openAdd(){modalBody.innerHTML=`<h2>Adicionar parada</h2><div class="field"><label>Nome / cliente</label><input id="newName" placeholder="Ex.: Maria"></div><div class="field"><label>Endereço</label><input id="newAddress" placeholder="Rua, número, bairro, cidade"></div><div class="field"><label>Observação</label><textarea id="newNote" rows="2" placeholder="Pedido, horário, detalhes..."></textarea></div><button id="createStop" class="primary full">Adicionar parada</button>`;modal.classList.remove("hidden");createStop.onclick=addStop}
async function addStop(){let name=newName.value.trim(),address=newAddress.value.trim(),note=newNote.value.trim();if(!address)return alert("Digite o endereço.");createStop.disabled=true;createStop.textContent="Localizando…";try{let r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=br&q=${encodeURIComponent(address)}`),d=await r.json();if(!d.length)throw 0;let s={id:crypto.randomUUID(),name:name||d[0].display_name.split(",")[0],address,lat:+d[0].lat,lon:+d[0].lon,status:"pending",note};stops.push(s);save();closeModal();render();map.setView([s.lat,s.lon],15);if(active){await recalcRemaining()} }catch(e){alert("Não encontrei esse endereço. Tente rua, número, bairro e cidade.")}createStop.disabled=false;createStop.textContent="Adicionar parada"}
function getPos(){return new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(p=>res({lat:p.coords.latitude,lon:p.coords.longitude}),rej,{enableHighAccuracy:true,timeout:10000}))}
function dist(a,b){let R=6371000,p=Math.PI/180,p1=a.lat*p,p2=b.lat*p,dl=(b.lat-a.lat)*p,do1=(b.lon-a.lon)*p,h=Math.sin(dl/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(do1/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
function nn(items,o){let left=[...items],cur=o,out=[];while(left.length){let bi=0,bd=1e30;left.forEach((s,i)=>{let d=dist(cur,s);if(d<bd){bd=d;bi=i}});let n=left.splice(bi,1)[0];out.push(n);cur=n}return out}
async function calculate(items,origin){if(!items.length)return;let ord=nn(items,origin),coords=[[origin.lon,origin.lat],...ord.map(s=>[s.lon,s.lat])].map(x=>x.join(",")).join(";");let r=await fetch(`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson`),d=await r.json();if(!d.routes?.length)throw 0;if(routeLayer)map.removeLayer(routeLayer);routeLayer=L.geoJSON(d.routes[0].geometry,{style:{weight:6}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[25,25]});orderIds=ord.map(s=>s.id);localStorage.setItem(ORDER,JSON.stringify(orderIds));routeSummary.textContent=`${ord.length} paradas • ${(d.routes[0].distance/1000).toFixed(1)} km • ~${Math.round(d.routes[0].duration/60)} min`;render()}
async function recalcRemaining(){try{let o=await getPos();await calculate(remaining(),o)}catch(e){alert("Não consegui recalcular. Verifique localização e internet.")}}
async function makeRoute(status=null){try{let o=await getPos(),items=stops.filter(s=>!status? s.status!=="completed":s.status===status);if(!items.length)return alert("Não há paradas para essa rota.");await calculate(items,o);active=true;localStorage.setItem(ACTIVE,"1");render()}catch(e){alert("Não foi possível calcular a rota agora.")}}
function quickComplete(id){let s=stops.find(x=>x.id===id);if(s){s.status="completed";save();recalcRemaining()}}
function navigateTo(id){let s=stops.find(x=>x.id===id);if(s)location.href=`https://maps.apple.com/?daddr=${s.lat},${s.lon}`}
optimizeRemaining.onclick=()=>makeRoute();pendingRoute.onclick=()=>makeRoute("pending");returnRoute.onclick=()=>makeRoute("returnLater");startRoute.onclick=()=>{active=true;localStorage.setItem(ACTIVE,"1");render();let n=orderedRemaining()[0];if(n)navigateTo(n.id)};
addDuring.onclick=openAdd;filterBtn.onclick=()=>{let v=prompt("Digite: pending, returnLater, notHome ou vazio para todas.",filter);if(v!==null){filter=["pending","returnLater","notHome"].includes(v)?v:"";render()}};
themeBtn.onclick=()=>{document.body.classList.toggle("dark");document.body.classList.toggle("light");let d=document.body.classList.contains("dark");localStorage.setItem("rs-theme",d?"dark":"light");themeBtn.textContent=d?"☀":"☾"};
if(localStorage.getItem("rs-theme")==="dark"){document.body.classList.add("dark");themeBtn.textContent="☀"}
render();
